"""24 KernelBench-derived workloads for the `triton_source` backend (D8).

Twelve level-1 and twelve level-2 KernelBench tasks, stratified by op family
and screened against the robust-kbench contamination criteria, converted to
the sandbox contract (no-arg `Model` + CUDA fp32 `get_inputs`). The data
lives in ``kernelbench_manifest.json`` next to this module — generated by
``scripts/kernelbench_select.py``, which also documents every exclusion.

Each manifest entry carries the adapted reference source, the banned-API
pattern list for lint gate g4 (derived from the ops in the task name), the
input shapes the backend's cheap `analyze()` records, and the symbolic
shape template (``metadata["holdout"]``) the D10 holdout generator
parameterizes. Registered with `register_workload_safely` (the
integration-example idiom) so test-harness module reloads never trip
duplicate-id errors.

The reference sources only touch torch/CUDA inside the sandbox subprocess,
so this module imports cleanly on CPU-only boxes.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from compilagent.core.workload import (
    BenchmarkBudget,
    DtypePolicy,
    ShapePolicy,
    ToleranceConfig,
    WorkloadInstance,
    WorkloadKind,
    WorkloadSpec,
)
from compilagent.core.workload_registry import register_workload_safely

_BUDGET = BenchmarkBudget(warmup=25, repetitions=100, max_seconds=240.0)
_TOLERANCE = ToleranceConfig(atol=1e-4, rtol=1e-3, notes="fp32 E2a gate g2")

_MANIFEST_PATH = Path(__file__).with_name("kernelbench_manifest.json")


def _spec_from_entry(entry: dict[str, Any]) -> WorkloadSpec:
    input_shapes = {k: list(v) for k, v in entry["input_shapes"].items()}
    first_shape = next(iter(input_shapes.values()), [1])
    return WorkloadSpec(
        id=entry["workload_id"],
        title=entry["title"],
        description=entry["description"],
        kind=WorkloadKind.KERNEL,
        backend_id="triton_source",
        dtype_policy=DtypePolicy(activation_dtype="fp32", param_dtype="fp32"),
        shape_policy=ShapePolicy(
            batch_size=int(first_shape[0]),
            extra={"input_shapes": dict(input_shapes)},
        ),
        tolerance=_TOLERANCE,
        budget=_BUDGET,
        metadata={
            "reference_module_source": entry["reference_module_source"],
            "banned_patterns": list(entry["banned_patterns"]),
            "input_shapes": dict(input_shapes),
            "input_dtypes": ["fp32"] * len(input_shapes),
            "op_signature": entry["op_signature"],
            "holdout": entry["holdout"],
            "kernelbench": {
                "level": entry["level"],
                "kb_index": entry["kb_index"],
                "kb_file": entry["kb_file"],
                "family": entry["family"],
            },
        },
    )


def _register(spec: WorkloadSpec) -> None:
    @register_workload_safely(spec)
    def _build(s: WorkloadSpec) -> WorkloadInstance:
        # The triton_source backend evaluates everything inside its
        # subprocess sandbox; the in-process forward is never invoked.
        return WorkloadInstance(
            spec=s,
            forward=lambda: None,
            example_inputs=(),
            metadata={"source_path": __file__},
        )


def _load_manifest() -> dict[str, Any]:
    return json.loads(_MANIFEST_PATH.read_text(encoding="utf-8"))


_ids: list[str] = []
for _entry in _load_manifest()["selected"]:
    _register(_spec_from_entry(_entry))
    _ids.append(_entry["workload_id"])

KB_WORKLOAD_IDS: tuple[str, ...] = tuple(_ids)
